# Generated by Django 4.1.4 on 2022-12-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='image',
            field=models.ImageField(default=None, upload_to='image'),
        ),
    ]
