# Generated by Django 4.1.4 on 2022-12-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0002_user_data_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='image1',
            field=models.ImageField(default=None, upload_to='image'),
        ),
        migrations.AddField(
            model_name='user_data',
            name='image2',
            field=models.ImageField(default=None, upload_to='image'),
        ),
        migrations.AddField(
            model_name='user_data',
            name='image3',
            field=models.ImageField(default=None, upload_to='image'),
        ),
    ]
